/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2023-12-22 02:26:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/Users/anjaehun/Desktop/spaceF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HotelPJT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/anjaehun/Desktop/spaceF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HotelPJT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1703085759101L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        h1, h2, h3, h4{\r\n");
      out.write("            margin-top: -5px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("            font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            margin: 200px auto;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            flex-flow: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        section{\r\n");
      out.write("            max-width: 1032px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-left: 24px;\r\n");
      out.write("            padding-right: 24px;\r\n");
      out.write("            border: 1px solid #717171;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        button{\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .account{\r\n");
      out.write("            font-size: 32px !important;\r\n");
      out.write("            font-weight: 600 !important;\r\n");
      out.write("            line-height: 36px !important;\r\n");
      out.write("        }\r\n");
      out.write("        .title{\r\n");
      out.write("            margin: 8px 0 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .title > span{\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .title > span > a{\r\n");
      out.write("            color: black;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .loginbox{\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        input{\r\n");
      out.write("            border: 1px solid #717171;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"email\"], input[type=\"tel\"]{\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            padding-left: 8px;\r\n");
      out.write("            border-radius:5px;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"], button{\r\n");
      out.write("            width: 420px;\r\n");
      out.write("            background-color: #460479;\r\n");
      out.write("            color: white;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            opacity: 20%;\r\n");
      out.write("            text-decoration-line: none;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"]:hover, button:hover{\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            opacity: 100%;\r\n");
      out.write("            transition-duration: 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .logo {\r\n");
      out.write("        	cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .setu{\r\n");
      out.write("        	font-size: 15px;\r\n");
      out.write("        	color: gray;\r\n");
      out.write("        }\r\n");
      out.write("        .errors{\r\n");
      out.write("        	font-size: 15px;\r\n");
      out.write("        	color: red;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("		  margin: 20px;\r\n");
      out.write("		  outline: none;\r\n");
      out.write("		}\r\n");
      out.write("		.custom-btn {\r\n");
      out.write("		  width: 130px;\r\n");
      out.write("		  height: 40px;\r\n");
      out.write("		  padding: 10px 25px;\r\n");
      out.write("		  border: 0.5px solid gray;\r\n");
      out.write("		  font-family: 'Lato', sans-serif;\r\n");
      out.write("		  font-weight: 500;\r\n");
      out.write("		  background: transparent;\r\n");
      out.write("		  cursor: pointer;\r\n");
      out.write("		  transition: all 0.3s ease;\r\n");
      out.write("		  position: relative;\r\n");
      out.write("		  display: inline-block;\r\n");
      out.write("		}\r\n");
      out.write("		.btn-3 {\r\n");
      out.write("  line-height: 39px;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write(".btn-3:hover{\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  color: #000;\r\n");
      out.write("}\r\n");
      out.write(".btn-3 span {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".btn-3:before,\r\n");
      out.write(".btn-3:after {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  background: gray;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".btn-3:before {\r\n");
      out.write("  height: 0%;\r\n");
      out.write("  width: 2px;\r\n");
      out.write("}\r\n");
      out.write(".btn-3:after {\r\n");
      out.write("  width: 0%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("}\r\n");
      out.write(".btn-3:hover:before {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".btn-3:hover:after {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".btn-3 span:before,\r\n");
      out.write(".btn-3 span:after {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  right: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: gray;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".btn-3 span:before {\r\n");
      out.write("  width: 2px;\r\n");
      out.write("  height: 0%;\r\n");
      out.write("}\r\n");
      out.write(".btn-3 span:after {\r\n");
      out.write("  width: 0%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("}\r\n");
      out.write(".btn-3 span:hover:before {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".btn-3 span:hover:after {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<button class=\"custom-btn btn-3\" onclick=\"history.back()\" style=\"text-decoration-line:none;\" >\r\n");
      out.write("		<span> <- Go Back</span></button>\r\n");
      out.write("    <section id=\"loginform\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div style=\"margin: 20px 0px 40px 0;\">\r\n");
      out.write("            <img class=\"logo\" alt width=\"130\" height=\"114\"\r\n");
      out.write("             src=\"https://www.planit.jp/wp-content/uploads/2020/02/Transparent-Logo-300x261.png\"\r\n");
      out.write("              onclick=\"location.href='master'\" >\r\n");
      out.write("                <div class=\"account\">会員ログイン</div>\r\n");
      out.write("                <div class=\"errors\">\r\n");
      out.write("                		<br>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form style=\"width: 460px\" method=\"post\">\r\n");
      out.write("            <div class=\"loginbox\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"email\" name=\"email\" placeholder=\"emailを入力してください。\" required=\"required\"/>\r\n");
      out.write("        	    <input type=\"tel\" name=\"phone_num\" placeholder=\"電話番号を入力してください。\"  required=\"required\" />\r\n");
      out.write("\r\n");
      out.write("        	    <div class=\"setu\" style=\"margin-top: 10px; margin-bottom: 10px;\">電話や携帯メールで電話番号を確認します。<br>\r\n");
      out.write("        	    											 一般文字メッセージ料金とデータ料金がかかります。</div>\r\n");
      out.write("        	    <input type=\"submit\" id=\"b1\" value=\"Log In\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <button style=\"margin-bottom: 15px; background-color: black;\" onclick=\"location.href='join'\">会員登録</button>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/login.jsp(194,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
