/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2023-12-22 05:47:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1703211760000L));
    _jspx_dependants.put("jar:file:/Users/anjaehun/Desktop/spaceF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HotelPJT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/anjaehun/Desktop/spaceF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HotelPJT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1703085759101L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>여행은 살아보는 거야 - 에어비앤비</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("   <header>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img class=\"logo\" alt width=\"124\" height=\"53\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\"></a>\n");
      out.write("        <nav class=\"midtag\">\n");
      out.write("            <div class=\"bnt\">\n");
      out.write("                <div>부산에서</div>\n");
      out.write("                <div>언제든 일주일</div>\n");
      out.write("                <div style=\"color: grey; font-size: 13px;\">게스트 추가</div>\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/빨간돋보기.png\" style=\"border-radius: 25px;\"></div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <nav>\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </nav>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <div class=\"modal hidden\">\n");
      out.write("        <div class=\"modal_overlay\"></div>\n");
      out.write("        <div class=\"modal_content\">\n");
      out.write("        	<button id=\"closebtn\" style=\"width: 25px;\">X</button>\n");
      out.write("        	<div><div style=\"padding: 10px 30px; font-size: 15px; margin-left: 0;\">로그인 또는 회원가입</div></div>\n");
      out.write("\n");
      out.write("		<section id=\"loginform\">\n");
      out.write("		        <div>\n");
      out.write("		            <div style=\"margin: 20px 0px 40px 0;\">\n");
      out.write("		            <img class=\"logo\" alt width=\"130\" height=\"114\"\n");
      out.write("		             src=\"https://www.planit.jp/wp-content/uploads/2020/02/Transparent-Logo-300x261.png\"\n");
      out.write("		              onclick=\"location.href='master'\" >\n");
      out.write("		                <div class=\"account\">会員ログイン</div>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		        <form style=\"width: 460px\">\n");
      out.write("		            <div class=\"loginbox\">\n");
      out.write("		                <input type=\"email\" name=\"host_email\" placeholder=\"emailを入力してください。\"/>\n");
      out.write("		        	    <input type=\"tel\" name=\"host_phoneNum\" placeholder=\"電話番号を入力してください。\"  />\n");
      out.write("		        	    <div style=\"margin-top: 10px; margin-bottom: 10px;\">電話や携帯メールで電話番号を確認します。 一般文字<br>メッセージ料金とデータ料金がかかります。</div>\n");
      out.write("		        	    <input type=\"submit\" id=\"b1\" value=\"Log In\" />\n");
      out.write("		            </div>\n");
      out.write("		        </form>\n");
      out.write("		        <button style=\"margin-bottom: 15px; background-color: black;\" onclick=\"location.href='join'\">会員登録</button>\n");
      out.write("		    </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("        	</div>\n");
      out.write("\n");
      out.write("        	<form id=\"authForm\" class=\"hidden\">\n");
      out.write("				<input type=\"text\" maxlength=\"6\" id=\"rpw\" name=\"authNumber\"  placeholder=\"인증 번호를 입력하세요\">\n");
      out.write("        		<input type=\"submit\" id=\"b3\">\n");
      out.write("        	</form>\n");
      out.write("\n");
      out.write("        	<ul id=\"none\">\n");
      out.write("					<li onclick=\"kakaoLogin();\">\n");
      out.write("						<a href=\"javascript:void(0)\"><span><img src=\"https://www.gb.go.kr/Main/Images/ko/member/certi_kakao_login.png\" /></span></a>\n");
      out.write("					</li>\n");
      out.write("			</ul>\n");
      out.write("			<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\n");
      out.write("			<script>\n");
      out.write("			    Kakao.init('6eb9a1e9581891af69cac432910920a3');\n");
      out.write("			    console.log(Kakao.isInitialized()); // sdk초기화여부판단\n");
      out.write("			    //카카오로그인\n");
      out.write("			    function kakaoLogin() {\n");
      out.write("			        Kakao.Auth.login({\n");
      out.write("			          success: function (response) {\n");
      out.write("			            Kakao.API.request({\n");
      out.write("			              url: '/v2/user/me',\n");
      out.write("			              success: function (response) {\n");
      out.write("// 			                console.log(response.kakao_account.email)\n");
      out.write("// 			                console.log(response.kakao_account.profile.nickname)\n");
      out.write("			                const ob = {\n");
      out.write("			                	'normal_name': response.kakao_account.profile.nickname,\n");
      out.write("			                	'normal_email': response.kakao_account.email\n");
      out.write("			                }\n");
      out.write("// 			                fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/kakao', {\n");
      out.write("// 			                	method: 'POST',\n");
      out.write("// 			                	body: JSON.stringify(ob),\n");
      out.write("// 			                	header: {\n");
      out.write("// 			                		'Content-type' : 'application/json; charset=utf-8'\n");
      out.write("// 			                	}\n");
      out.write("// 			                })\n");
      out.write("// 			                .then(resp => resp.text())\n");
      out.write("// 			                .then(text => {\n");
      out.write("// 			                	if(text == 1){\n");
      out.write("// 			                		console.log('세션에 있다')\n");
      out.write("// 			                	}\n");
      out.write("// 			                	else {\n");
      out.write("// 			                		console.log('세션에 없다')\n");
      out.write("// 			                	}\n");
      out.write("// 			                })\n");
      out.write("\n");
      out.write("						    kakaomap(response)\n");
      out.write("			              },\n");
      out.write("			              fail: function (error) {\n");
      out.write("			                console.log(error)\n");
      out.write("			              },\n");
      out.write("			            })\n");
      out.write("			          },\n");
      out.write("			          fail: function (error) {\n");
      out.write("			            console.log(error)\n");
      out.write("			          },\n");
      out.write("			        })\n");
      out.write("			      }\n");
      out.write("\n");
      out.write("			    function kakaomap(res) {\n");
      out.write("\n");
      out.write("			    	const account = res.kakao_account.email\n");
      out.write("			    	const nickname = res.properties.nickname\n");
      out.write("\n");
      out.write("			    	const user = {\n");
      out.write("			    			'normal_name': nickname,\n");
      out.write("			    			'normal_email': account\n");
      out.write("			    	}\n");
      out.write("// 			    	console.log(user)\n");
      out.write("\n");
      out.write("\n");
      out.write("					kakaoconfirm(user)\n");
      out.write("			    }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			    function kakaoconfirm(dto) {\n");
      out.write("			    	const url = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/kakaologin'\n");
      out.write("			    	const opt = {\n");
      out.write("			    			method: 'POST',\n");
      out.write("			    			body: JSON.stringify(dto),\n");
      out.write("							headers: {\n");
      out.write("								'Content-Type' : 'application/json; charset=utf-8'\n");
      out.write("							}\n");
      out.write("			    	}\n");
      out.write("			    	fetch(url,opt)\n");
      out.write("			    	.then(resp => resp.json())\n");
      out.write("			    	.then(row => {\n");
      out.write("			    		if(row == 1) {\n");
      out.write("			    			alert('로그인 성공')\n");
      out.write("			    			location.href = 'http://localhost:8080/real/'\n");
      out.write("			    		}else {\n");
      out.write("			    			alert('저희가 운영하는 사이트에서 필요한 데이터가 없습니다 회원가입페이지로 이동합니다.')\n");
      out.write("			    			location.href = 'http://localhost:8080/real/member/kakao'\n");
      out.write("			    		}\n");
      out.write("\n");
      out.write("			    	})\n");
      out.write("			    }\n");
      out.write("			    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("         const openButton = document.getElementById(\"open\")\n");
      out.write("\n");
      out.write("         const modal = document.querySelector(\".modal\")\n");
      out.write("         const overlay = modal.querySelector(\".modal_overlay\")\n");
      out.write("         const closebtn = document.getElementById(\"closebtn\")\n");
      out.write("\n");
      out.write("         const openModal = () => {\n");
      out.write("             modal.classList.remove(\"hidden\")\n");
      out.write("         }\n");
      out.write("         const closeModal = () => {\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        	 authForm.classList.add(\"hidden\")\n");
      out.write("        	 loginform.classList.remove(\"hidden\")\n");
      out.write("        	 authForm.reset()\n");
      out.write("        	 loginform.reset()\n");
      out.write("\n");
      out.write("             modal.classList.add(\"hidden\")\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         openButton.addEventListener(\"click\", openModal)\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("         closebtn.addEventListener(\"click\", closeModal)\n");
      out.write("         overlay.addEventListener(\"click\", closeModal)\n");
      out.write("\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("	<!-- 로그인 함수 -->\n");
      out.write("	<script>\n");
      out.write("		const b1 = document.getElementById('b1')\n");
      out.write("		const b3 = document.getElementById('b3')\n");
      out.write("		const authForm = document.getElementById('authForm')\n");
      out.write("\n");
      out.write("		const loginform = document.getElementById('loginform')\n");
      out.write("		loginform.addEventListener('submit', submitHandller)\n");
      out.write("\n");
      out.write("		function submitHandller(event) {\n");
      out.write("			event.preventDefault()\n");
      out.write("	// 		const normal_email = document.getElementById('normal_email')\n");
      out.write("	// 		const normal_phoneNum = document.getElementById('normal_phoneNum')\n");
      out.write("\n");
      out.write("			const formData = new FormData(event.target)\n");
      out.write("			const ob = {}\n");
      out.write("\n");
      out.write("			for(let key of formData.keys()) {\n");
      out.write("				ob[key] = formData.get(key)\n");
      out.write("			}\n");
      out.write("			console.log(ob)\n");
      out.write("			fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member', {\n");
      out.write("				method: 'POST',\n");
      out.write("				body: JSON.stringify(ob),\n");
      out.write("				headers: {\n");
      out.write("					'Content-Type' : 'application/json; charset=utf-8'\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("			.then(resp => resp.text())\n");
      out.write("			.then(text => {\n");
      out.write("				if(text == 'true') {\n");
      out.write("					const ob2 = { }\n");
      out.write("					for(let key of formData.keys()) {\n");
      out.write("						ob2[key] = formData.get(key)\n");
      out.write("					}\n");
      out.write("					fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/inzung', {\n");
      out.write("						method: 'POST',\n");
      out.write("						body: JSON.stringify(ob2),\n");
      out.write("						headers: {\n");
      out.write("							'Content-Type' : 'application/json; charset=utf-8'\n");
      out.write("						}\n");
      out.write("					})\n");
      out.write("					.then(resp => resp.text())\n");
      out.write("					.then(text => {\n");
      out.write("						if(text == '성공') {\n");
      out.write("							loginform.classList.add('hidden')\n");
      out.write("							authForm.classList.remove('hidden')\n");
      out.write("						}\n");
      out.write("					})\n");
      out.write("\n");
      out.write("					alert('인증번호 발송')\n");
      out.write("				}\n");
      out.write("				if(text == 'false') {\n");
      out.write("					alert('이메일과 전화번호가 일치하지 않습니다')\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("		}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		authForm.addEventListener('submit', (event) => {\n");
      out.write("			event.preventDefault()\n");
      out.write("			const formData2 = new FormData(event.target)\n");
      out.write("			const ob = {}\n");
      out.write("			for(let key of formData2.keys()) {\n");
      out.write("				ob[key] = formData2.get(key)\n");
      out.write("			}\n");
      out.write("			console.log(ob)\n");
      out.write("			fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/inzung3', {\n");
      out.write("				method: 'POST',\n");
      out.write("					body: JSON.stringify(ob),\n");
      out.write("					headers: {\n");
      out.write("						'Content-Type' : 'application/json; charset=utf-8'\n");
      out.write("					}\n");
      out.write("			})\n");
      out.write("			.then(resp => resp.text())\n");
      out.write("			.then(text => {\n");
      out.write("				alert(text)\n");
      out.write("				if(text == \"인증 성공\") {\n");
      out.write("					location.reload();\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("		})\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- 로그아웃 함수 -->\n");
      out.write("	<script>\n");
      out.write("		const logout = document.getElementById('logout')\n");
      out.write("		logout.addEventListener('click', logoutHandller)\n");
      out.write("\n");
      out.write("		function logoutHandller(event) {\n");
      out.write("\n");
      out.write("			var is = confirm('정말 로그아웃 하시겠습니까?')\n");
      out.write("\n");
      out.write("			if(is) {\n");
      out.write("				location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout'\n");
      out.write("				return ture\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			else {\n");
      out.write("				return false\n");
      out.write("			}\n");
      out.write("\n");
      out.write("\n");
      out.write("		}\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style_JaeHun.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	const cpath = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	const product_idx = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	/*          position: sticky;  */\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	background: white;\r\n");
      out.write("	color: black;\r\n");
      out.write("	padding-left: 20px;\r\n");
      out.write("	padding-right: 20px;\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("	padding-bottom: 0px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	/*          border-bottom: 1px solid rgb(218, 209, 209);  */\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bnt { */\r\n");
      out.write("	font-family: 'Nanum Gothic';\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	height: 43px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	border: 1.3px solid rgb(235, 232, 232);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bnt>div:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bnt>div {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login {\r\n");
      out.write("	color: rgb(135, 128, 128);\r\n");
      out.write("	font-size: small;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login2 {\r\n");
      out.write("	color: rgb(135, 128, 128);\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	border: 1px solid rgb(135, 128, 128);\r\n");
      out.write("	width: 155px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-left: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login2:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".midtag>div {\r\n");
      out.write("	border: 1.5px solid rgb(218, 209, 209);\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".midtag>div>div>div {\r\n");
      out.write("	border: 1px solid rgb(118, 108, 108);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav>div {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-left: 3px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	all: unset;\r\n");
      out.write("	background-color: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("	background-color: rgb(218, 209, 209);\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	width: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	z-index: 4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal_overlay {\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.6);\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal_content {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-flow: column;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	padding: 10px 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	width: 560px;\r\n");
      out.write("	height: 670px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hidden {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal_content>div {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	margin-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".putlogin {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-flow: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 리모컨 */\r\n");
      out.write("\r\n");
      out.write(".remocon {\r\n");
      out.write("   border: 1px dashed black;\r\n");
      out.write("   border-radius: 12px;\r\n");
      out.write("   padding: 24px;\r\n");
      out.write("   position: sticky;\r\n");
      out.write("   width: 373px;\r\n");
      out.write("   height: 459px;\r\n");
      out.write("   top: 200px;\r\n");
      out.write("   margin-top: 15px;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reservation {\r\n");
      out.write("   padding: 13px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   color: white;\r\n");
      out.write("   border-radius: 12px;\r\n");
      out.write("   background-color: #b32505;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".check {\r\n");
      out.write("   border: 1px solid black;\r\n");
      out.write("   border-radius: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("   font-size: 22px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   margin-bottom: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".check>.checkin, .check>.checkout {\r\n");
      out.write("   border: 1px solid black;\r\n");
      out.write("   border-radius: 12px;\r\n");
      out.write("   width: 140.67px;\r\n");
      out.write("   height: 46px;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 25px 12px 10px;\r\n");
      out.write("   display: flex;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".체크인렙 {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".체크인렙>.checkin, .체크인렙>.checkout {\r\n");
      out.write("   border: 1px solid black;\r\n");
      out.write("   padding: 15px 10px 12px;\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: center;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("   flex: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".guest {\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("   border: 1px solid black;\r\n");
      out.write("   position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".guest>.guest_dropdown {\r\n");
      out.write("   background: rgb(255, 255, 255);\r\n");
      out.write("   border-radius: 4px;\r\n");
      out.write("   box-shadow: rgb(0 0 0/ 15%) 0px 2px 6px, rgb(0 0 0/ 7%) 0px 0px 0px 1px;\r\n");
      out.write("   box-sizing: border-box;\r\n");
      out.write("   margin-bottom: 16px;\r\n");
      out.write("   min-width: 280px;\r\n");
      out.write("   padding: 16px;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("   width: 100% !important;\r\n");
      out.write("   z-index: 999 !important;\r\n");
      out.write("   right: 0px !important;\r\n");
      out.write("   width: 322.33px;\r\n");
      out.write("   height: 397px;\r\n");
      out.write("   flex-flow: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".guest > .guest_dropdown> div {\r\n");
      out.write("   height: 296px;\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown> div > .adult {\r\n");
      out.write("\r\n");
      out.write("	margin-top: 8px;\r\n");
      out.write("	margin-bottom: 24px;\r\n");
      out.write("	height: 42px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .adult > div {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .adult > div,\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet > div {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet {\r\n");
      out.write("\r\n");
      out.write("	height: 42px;\r\n");
      out.write("	margin-top: 24px;\r\n");
      out.write("	margin-bottom: 24px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet > div {\r\n");
      out.write("\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .adult > div > .left,\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet > div > .left {\r\n");
      out.write("\r\n");
      out.write("	width: 186.328px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .adult > div > .left > div:nth-child(1),\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet > div > .left > div:nth-child(1) {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".guest > .guest_dropdown > div > .adult > div > .left > div:nth-child(2),\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet > div > .left > div:nth-child(2) {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .info {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	padding-bottom: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".guest > .guest_dropdown > div > .close{\r\n");
      out.write("	float: right;\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".guest > .guest_dropdown > div > .adult > div > .right,\r\n");
      out.write(".guest > .guest_dropdown > div > .childbabypet > div > .right {\r\n");
      out.write("\r\n");
      out.write("	width: 110px;\r\n");
      out.write("	height: 32px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right {\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write(".right > div {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right > div > div {\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	padding: 6px;\r\n");
      out.write("}\r\n");
      out.write(".right>div>div>span {\r\n");
      out.write("   display: flex;\r\n");
      out.write("    justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write(".right > div > button > span {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: center;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("}\r\n");
      out.write(".right > div > div > button > span {\r\n");
      out.write("	width:22px;\r\n");
      out.write("	height: 22px;\r\n");
      out.write("}\r\n");
      out.write(".right > div > button {\r\n");
      out.write("	width: 32px;\r\n");
      out.write("	height: 32px;\r\n");
      out.write("	border: 1px solid grey;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("/* 리모컨 끝 */\r\n");
      out.write("\r\n");
      out.write(".hidden{\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/view.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div class=\"main1\">\r\n");
      out.write("			<div class=\"main1_1\">\r\n");
      out.write("				<div class=\"main1_head\">\r\n");
      out.write("					<section class=\"section1\">\r\n");
      out.write("						<div class=\"top\">\r\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/svg/translation.svg\"></span>\r\n");
      out.write("							<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"bottom\">\r\n");
      out.write("							<div class=\"left\">\r\n");
      out.write("								<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/svg/star.svg\"></span> <span> ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write(" <!--                                    														(46.666 -   0.666666666	)  * 0.1\r\n");
      out.write("																								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${star}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" (반올림 한 결과값) --> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${starnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ★\r\n");
      out.write("								</span> <span class=\"jum\">·</span> <span>\r\n");
      out.write("									<div>후기 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_reviewcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개</div>\r\n");
      out.write("								</span> <span class=\"jum\">·</span> <span>호스트</span> <span class=\"jum\">·</span>\r\n");
      out.write("								<span>\r\n");
      out.write("									<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_addrs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",부산, 한국</div>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"right\">\r\n");
      out.write("								<div class=\"share\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/svg/share.svg\"></span><span>공유하기</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"save\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/svg/save.svg\"></span><span>저장</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"main2\">\r\n");
      out.write("			<div class=\"main2_1\">\r\n");
      out.write("				<div class=\"main2_2\">\r\n");
      out.write("					<div class=\"main2_photo\">\r\n");
      out.write("						<div class=\"photo1\">\r\n");
      out.write("							<div class=\"photo1_1\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/1.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"photo2\">\r\n");
      out.write("							<div class=\"photo2_1\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/2.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"photo2_1\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/3.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"photo2\">\r\n");
      out.write("							<div class=\"photo2_2\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/4.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"photo2_2\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.product_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/5.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 	const root2 = document.getElementById('root2')\r\n");
      out.write("	const leftp = document.getElementById('leftp')\r\n");
      out.write("	const rightp = document.getElementById('rightp')\r\n");
      out.write("// 	const offset = root2.getAttribute('offset')\r\n");
      out.write("\r\n");
      out.write("	const root2 = document.getElementById('root2')\r\n");
      out.write("	const offset = root2.getAttribute('offset')\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	window.addEventListener('load', loadHandler2)\r\n");
      out.write("	window.addEventListener('load', pageHandler)\r\n");
      out.write("	leftp.addEventListener('click', leftpHandler)\r\n");
      out.write("	rightp.addEventListener('click', rightpHandler)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	const guest = document.querySelector('.guest')\r\n");
      out.write("	const gdd = document.querySelector('.guest > .guest_dropdown')\r\n");
      out.write("	const main = document.querySelector('.main')\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function guestCilck(event) {\r\n");
      out.write("	   	gdd.classList.remove('hidden')\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	function closeguest(event){\r\n");
      out.write("		   if(event.target.className == 'close')\r\n");
      out.write("		   gdd.className.add('hidden')\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	guest.addEventListener('click', guestCilck)\r\n");
      out.write("	guest.addEventListener('click', closeguest)\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/header.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/header.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/header.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/header.jsp(28,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty login }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"login\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginH\">호스트되기</a></div>\n");
          out.write("            <div id=\"open\" class=\"login2\">로그인 / 회원가입</div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/header.jsp(32,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty login }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"login1\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/mypage\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.normal_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          out.write(' ');
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.normal_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</a></div>		<!-- dto.normal, dto객체 하나를 login이라는 이름으로 섹션에 저장후 이름 가져옴 -->\n");
          out.write("\n");
          out.write("            <div id=\"logout\" class=\"login2\">로그아웃</div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/view.jsp(370,72) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("star");
      // /WEB-INF/views/view.jsp(370,72) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/view.jsp(370,72) '${dto.product_score / dto.product_reviewcnt}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dto.product_score / dto.product_reviewcnt}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/view.jsp(371,77) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setVar("starnum");
      // /WEB-INF/views/view.jsp(371,77) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      // /WEB-INF/views/view.jsp(371,77) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("0.0");
      // /WEB-INF/views/view.jsp(371,77) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${((star*10) - ((star*10)%1)) * (1/10)} ", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvar_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }
}
