/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2023-12-20 17:03:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class master_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/anjaehun/Desktop/spaceF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Testhotel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/anjaehun/Desktop/spaceF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Testhotel/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1329370132000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1703085759101L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar", Long.valueOf(1703085758236L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>福岡なら - PlanIt</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin-top: 0px;\r\n");
      out.write("        margin-bottom: 0px;\r\n");
      out.write("        margin-left: 0px;\r\n");
      out.write("        margin-right: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    header {\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        height: 80px;\r\n");
      out.write("        background: white;\r\n");
      out.write("        color: black;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        padding-right: 20px;\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        padding-bottom: 0px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        border-bottom: 1px solid rgb(218, 209, 209);\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("    }\r\n");
      out.write("    .logo:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .bnt {\r\n");
      out.write("        font-family: 'Nanum Gothic';\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        width: 350px;\r\n");
      out.write("        height: 43px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        border: 1.3px solid rgb(235, 232, 232);\r\n");
      out.write("    }\r\n");
      out.write("    .bnt > div:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .bnt > div {\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("    }\r\n");
      out.write("    .login {\r\n");
      out.write("        color: rgb(135, 128, 128);\r\n");
      out.write("        font-size: small;\r\n");
      out.write("    }\r\n");
      out.write("    .login:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .login2 {\r\n");
      out.write("        color: rgb(135, 128, 128);\r\n");
      out.write("        font-size: small;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        border: 1px solid rgb(135, 128, 128);\r\n");
      out.write("        width: 155px;\r\n");
      out.write("        height: 25px;\r\n");
      out.write("        line-height: 25px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-left: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .login2:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .midtag > div {\r\n");
      out.write("        border: 1.5px solid rgb(218, 209, 209);\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    .midtag > div > div > div {\r\n");
      out.write("        border: 1px solid rgb(118, 108, 108);\r\n");
      out.write("    }\r\n");
      out.write("    div {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin-left: 16px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    nav {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .category {\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 60px;\r\n");
      out.write("        background: white;\r\n");
      out.write("        color: black;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        padding-right: 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-evenly;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        margin-top: -30px;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        margin-left: 0px;\r\n");
      out.write("        margin-right: 0px;\r\n");
      out.write("        border-bottom: 1px solid rgb(218, 209, 209);\r\n");
      out.write("        max-height: 80px;\r\n");
      out.write("    }\r\n");
      out.write("    .category > div {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .ca:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        border-bottom: 2.5px solid black;\r\n");
      out.write("    }\r\n");
      out.write("    .pillter {\r\n");
      out.write("        padding-top: 15px ;\r\n");
      out.write("    }\r\n");
      out.write("    .pillter:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-flow: column;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .menu > img {\r\n");
      out.write("        padding-bottom: 10px;\r\n");
      out.write("        transition: all 0.2s linear;\r\n");
      out.write("    }\r\n");
      out.write("    .menu > img:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transform: scale(1.05);\r\n");
      out.write("    }\r\n");
      out.write("    .menu >  div > div:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    main {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        justify-items: center;\r\n");
      out.write("    }\r\n");
      out.write("    .wrap {\r\n");
      out.write("        max-width: 1700px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-flow: wrap;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("    }\r\n");
      out.write("    .itemName {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin-left: 0px;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        padding-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .itemName > div {\r\n");
      out.write("        font-size: medium;\r\n");
      out.write("    }\r\n");
      out.write("    .sub {\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        color: grey;\r\n");
      out.write("        font-weight: lighter;\r\n");
      out.write("    }\r\n");
      out.write("    .price {\r\n");
      out.write("        padding-top: 15px;\r\n");
      out.write("        font-size: medium;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("    }\r\n");
      out.write("    .찜 {\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: 15px;\r\n");
      out.write("        top: 5px;\r\n");
      out.write("        color: rgb(236, 109, 130);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        border-top: 1px solid rgb(218, 209, 209);\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        padding-bottom: 20px;\r\n");
      out.write("        padding-left: 100px;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 91%;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .downst > div{\r\n");
      out.write("        font-size: smaller;\r\n");
      out.write("        color: rgb(163, 162, 162);\r\n");
      out.write("    }\r\n");
      out.write("    .downner {\r\n");
      out.write("        width: 1650px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        padding-right: 10px;\r\n");
      out.write("        border-bottom: 1px solid rgb(218, 217, 217);\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        padding-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function removeCheck() {\r\n");
      out.write("	 if (confirm(\"本当にログアウトしますか。\") == true){\r\n");
      out.write("		 window.location.href = 'http://localhost:8080/hotel/logout';//확인\r\n");
      out.write("	 }\r\n");
      out.write("	 else{   //취소\r\n");
      out.write("	     return false;\r\n");
      out.write("	 }\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/function.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <img class=\"logo\" alt width=\"130\" height=\"114\" src=\"https://www.planit.jp/wp-content/uploads/2020/02/Transparent-Logo-300x261.png\"\r\n");
      out.write("         onclick=\"location.href='master'\" >\r\n");
      out.write("        <nav class=\"midtag\">\r\n");
      out.write("            <div class=\"bnt\">\r\n");
      out.write("                <div>どこでも</div>\r\n");
      out.write("                <div>いつでも</div>\r\n");
      out.write("                <div style=\"color: grey; font-size: 13px;\">福岡で</div>\r\n");
      out.write("                <div><img src=\"resources/img/redglass.png\" style=\"border-radius: 25px;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("         ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"remocon\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"category\">\r\n");
      out.write("\r\n");
      out.write("		<div onclick=\"location.href='master'\" >SHOW ALL</div>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"master\" method=\"post\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"hotel_cat\" value=\"POOL\">\r\n");
      out.write("		    <input type=\"image\" name=\"submit\" class=\"ca\" src=\"resources/img/pool.png\" alt=\"POOL\" width=\"80\" height=\"80\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"master\" method=\"post\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"hotel_cat\" value=\"BEACH\">\r\n");
      out.write("		    <input type=\"image\" name=\"submit\" class=\"ca\" src=\"resources/img/beach.png\" alt=\"BEACH\" width=\"80\" height=\"80\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"master\" method=\"post\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"hotel_cat\" value=\"SNOW\">\r\n");
      out.write("		    <input type=\"image\" name=\"submit\" class=\"ca\" src=\"resources/img/snow.png\" alt=\"SNOW\" width=\"80\" height=\"80\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"master\" method=\"post\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"hotel_cat\" value=\"KAN\">\r\n");
      out.write("		    <input type=\"image\" name=\"submit\" class=\"ca\" src=\"resources/img/ryokan.png\" alt=\"KAN\" width=\"80\" height=\"80\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"master\" method=\"post\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"hotel_cat\" value=\"SIMA\">\r\n");
      out.write("		    <input type=\"image\" name=\"submit\" class=\"ca\" src=\"resources/img/dockdo.png\" alt=\"SIMA\" width=\"80\" height=\"80\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <img class=\"pillter\" src=\"resources/img/filter.png\" alt width=\"84\" height=\"48\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("        <br><br><br><br>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"downner\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>@ 2022 PlanIt, lnc.</div>\r\n");
      out.write("\r\n");
      out.write("                    <div>個人情報処理方針</div>\r\n");
      out.write("                    <div>利用規約</div>\r\n");
      out.write("                    <div>サイトマップ</div>\r\n");
      out.write("                    <div>韓国の変更された払い戻し政策</div>\r\n");
      out.write("                    <div>会社の詳細情報</div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>@ 日本語(JP)</div>\r\n");
      out.write("                    <div>\\ JPY</div>\r\n");
      out.write("                    <div>支援および参考資料</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"downst\">\r\n");
      out.write("                <div>웹사이트 제공자: PanIt Ireland UC, private unlimited company, 8 Hanover Quay Dublin 2, D02 DP23 Ireland | 이사: 安材訓, イソンジュン | VAT 번호: IE9827384L | 사업자 등록 번호: IE 511825 | 연락처: nackgee01@naver.com, 웹사이트, 080-4143-3261 | 호스팅 서비스 제공업체: 아마존 웹서비스 | 플랜잇은 통신판매</div>\r\n");
      out.write("                <div>중개자로 플랜잇 플랫폼을 통하여 게스트와 호스트 사이에 이루어지는 통신판매의 당사자가 아닙니다. 플랜잇 플랫폼을 통하여 예약된 숙소, 체험, 호스트 서비스에 관한 의무와 책임은 해당 서비스를 제공하는 호스트에게 있습니다.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("	window.addEventListener('load', loadHandler)\r\n");
      out.write("	window.addEventListener('scroll' , scrollHandler)\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/master.jsp(258,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userModel }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <nav>\r\n");
          out.write("            <div class=\"login\">予約者情報入力</div>\r\n");
          out.write("            <div class=\"login2\" onclick=\"location.href='login'\">氏名 / 携帯番号</div>\r\n");
          out.write("        </nav>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/master.jsp(265,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty userModel }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         <nav>\r\n");
          out.write("         	<div class=\"login\" onclick=\"location.href='modify'\">\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userModel.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"様</div>\r\n");
          out.write("			<div id=\"tblbutton\" class=\"login2\" type=\"button\" onclick=\"removeCheck()\">ログアウト</div>\r\n");
          out.write("		</nav>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/master.jsp(315,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("hotel");
      // /WEB-INF/views/master.jsp(315,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/master.jsp(315,2) '${hotelList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${hotelList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("	    	<div class=\"menu\">\r\n");
            out.write("	            <div class=\"menu\">\r\n");
            out.write("	                <img class=\"menu\" src=\"resources/img/");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(".webp\" alt width=\"300.8\" height=\"285.75\">\r\n");
            out.write("	                <div class=\"찜\">♥</div>\r\n");
            out.write("	                <div class=\"itemName\">\r\n");
            out.write("	                    <div>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</div>\r\n");
            out.write("	                    <div> 4.75 ★</div>\r\n");
            out.write("	                </div>\r\n");
            out.write("	                <div class=\"sub\">150km 距離</div>\r\n");
            out.write("	                <div class=\"sub\">8月 15日～21日</div>\r\n");
            out.write("	                <div class=\"price\"> \\39900円 / 泊</div>\r\n");
            out.write("	                <ul><br><br></ul>\r\n");
            out.write("	            </div>\r\n");
            out.write("        	</div>\r\n");
            out.write("\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/master.jsp(319,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.image_path }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/master.jsp(322,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.name }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
